apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: Opaque
data:
   DB_PASSWORD: cGFzc0B3b3Jk
   DB_HOST: bXlzcWwuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbA==
   DB_USER: cm9vdA==
---
apiVersion: v1
kind: Secret
metadata:
    name: aws-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQTJNWUM0Mk9TVVlGR09MMkU=
  AWS_SECRET_ACCESS_KEY: R1BxZkxHZFRrSTR6cnFkUW9mN3IwMFU3SmdBdEptbDRMcjduWGZrSw==
---
apiVersion: v1
kind: Secret
metadata:
    name: azure-secret
type: Opaque
data:
  AZURE_CLIENT_ID: OWM5YmIzYzgtMjAxMS00ZGEyLTg5YWYtNzVlZWRkNzhlODUw
  AZURE_TENANT_ID: YzVhYWFmNTUtN2U1Mi00ZjNlLTg4OGQtZDhjZGE2YmIxYTI3
  AZURE_CLIENT_SECRET: a0hKOFF+SG1CaWtvaUZsUnVlRkpRWXhXOGw2YmpiYk5lZTUtbmE2eQ==
  AZURE_SUBSCRIPTION_ID: ODczNzEwNGItOTgwOS00MmQzLTkxNDItOGYzNWNmZTM4OTE1
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL3JlZ2lzdHJ5LmdpdGxhYi5jb20iOnsKICAgICAgICAgICAgInVzZXJuYW1lIjoiOTg0NjM4MTkwMyIsCiAgICAgICAgICAgICJwYXNzd29yZCI6IkRldihTZWMpT3BzIiwKICAgICAgICAgICAgImF1dGgiOiJPVGcwTmpNNE1Ua3dNenBFWlhZb1UyVmpLVTl3Y3c9PSIKICAgICAgICB9CiAgICB9Cn0K
